apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: production
  labels:
    app: go-app
    env: prod
spec:
  selector:
    app: go-app
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort