apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-memory-usage
  namespace: default
  labels:
    app: prometheus
    release: prometheus
spec:
  groups:
  - name: kubernetes
    rules:
    - alert: ContainerHighMemoryUsage
      expr: (sum(container_memory_working_set_bytes{name!=""}) BY (instance, name) / sum(container_spec_memory_limit_bytes > 0) BY (instance, name) * 100) > 80
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Container High Memory usage (instance {{ $labels.instance }})
        description: "Container Memory usage is above 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"