apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-not-running
  namespace: default
  labels:
    app: prometheus
    release: prometheus
spec:
  groups:
  - name: kubernetes
    rules:
    - alert: PodNotRunning
      expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Failed|Unknown"}) > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Pod has been in a non-running state for more than 5 minutes"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been in a non-running state for longer than 5 minutes."