apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: development
  labels:
    app: go-app
    env: dev
spec:
  selector:
    app: go-app
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort